
class CoffeeData {
  int codingHours;
  int coffeeCupsPerDay;
  String coffeeTime;
  String codingWithoutCoffee;
  String coffeeType;
  String coffeeSolveBugs;
  String gender;
  String country;
  String ageRange;
  int id;

  String toString() {
    return id.toString();
  }

  CoffeeData(this.codingHours, this.coffeeCupsPerDay, this.coffeeTime, this.codingWithoutCoffee, this.coffeeType, this.coffeeSolveBugs, this.gender, this.country, this.ageRange, this.id);

  static final coffeeDataSmall = [new CoffeeData( 8 , 2 , "Before coding" , "Yes" , "Caffè latte" , "Sometimes" , "Female" , "Lebanon" , "18 to 29", 0),
    new CoffeeData( 3 , 2 , "Before coding" , "Yes" , "Americano" , "Yes" , "Female" , "Lebanon" , "30 to 39", 1) ,
    new CoffeeData( 5 , 3 , "While coding" , "No" , "Nescafe" , "Yes" , "Female" , "Lebanon" , "18 to 29" , 2),
    CoffeeData( 8 , 2 , "Before coding" , "No" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "NA" , 3 ) ,
    CoffeeData( 10 , 3 , "While coding" , "Sometimes" , "Turkish" , "No" , "Male" , "Lebanon" , "18 to 29" , 4 ) ,
    CoffeeData( 8 , 2 , "While coding" , "Sometimes" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 5 ) ,
    CoffeeData( 5 , 2 , "While coding" , "Yes" , "Nescafe" , "Sometimes" , "Male" , "Lebanon" , "NA" , 6 )];


  static final coffeeData = [CoffeeData( 8 , 2 , "Before coding" , "Yes" , "Caffè latte" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 0 ) ,
    CoffeeData( 3 , 2 , "Before coding" , "Yes" , "Americano" , "Yes" , "Female" , "Lebanon" , "30 to 39" , 1 ) ,
    CoffeeData( 5 , 3 , "While coding" , "No" , "Nescafe" , "Yes" , "Female" , "Lebanon" , "18 to 29" , 2 ) ,
    CoffeeData( 8 , 2 , "Before coding" , "No" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "NA" , 3 ) ,
    CoffeeData( 10 , 3 , "While coding" , "Sometimes" , "Turkish" , "No" , "Male" , "Lebanon" , "18 to 29" , 4 ) ,
    CoffeeData( 8 , 2 , "While coding" , "Sometimes" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 5 ) ,
    CoffeeData( 5 , 2 , "While coding" , "Yes" , "Nescafe" , "Sometimes" , "Male" , "Lebanon" , "NA" , 6 ) ,
    CoffeeData( 10 , 4 , "Before coding" , "Sometimes" , "Turkish" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 7 ) ,
    CoffeeData( 10 , 2 , "While coding" , "Yes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 8 ) ,
    CoffeeData( 10 , 2 , "While coding" , "Yes" , "Nescafe" , "No" , "Male" , "Lebanon" , "30 to 39" , 9 ) ,
    CoffeeData( 10 , 3 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 10 ) ,
    CoffeeData( 2 , 3 , "Before coding" , "Sometimes" , "Turkish" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 11 ) ,
    CoffeeData( 8 , 2 , "Before and while coding" , "No" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 12 ) ,
    CoffeeData( 9 , 3 , "While coding" , "Sometimes" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 13 ) ,
    CoffeeData( 6 , 1 , "Before coding" , "Yes" , "Nescafe" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 14 ) ,
    CoffeeData( 6 , 3 , "While coding" , "No" , "Americano" , "Yes" , "Female" , "Lebanon" , "30 to 39" , 15 ) ,
    CoffeeData( 10 , 3 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 16 ) ,
    CoffeeData( 6 , 4 , "While coding" , "Yes" , "Turkish" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 17 ) ,
    CoffeeData( 8 , 3 , "While coding" , "No" , "Nescafe" , "No" , "Male" , "Lebanon" , "18 to 29" , 18 ) ,
    CoffeeData( 3 , 1 , "In the morning" , "Yes" , "Nescafe" , "Sometimes" , "Female" , "Lebanon" , "30 to 39" , 19 ) ,
    CoffeeData( 3 , 3 , "While coding" , "Yes" , "Espresso (Short Black)" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 20 ) ,
    CoffeeData( 9 , 5 , "While coding" , "Sometimes" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 21 ) ,
    CoffeeData( 4 , 2 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 22 ) ,
    CoffeeData( 8 , 3 , "While coding" , "No" , "Turkish" , "No" , "Male" , "Lebanon" , "40 to 49" , 23 ) ,
    CoffeeData( 5 , 3 , "While coding" , "Sometimes" , "Cappuccino" , "Sometimes" , "Male" , "Lebanon" , "Under 18" , 24 ) ,
    CoffeeData( 6 , 3 , "While coding" , "Yes" , "Nescafe" , "No" , "Female" , "Lebanon" , "30 to 39" , 25 ) ,
    CoffeeData( 7 , 4 , "Before coding" , "Sometimes" , "Espresso (Short Black)" , "No" , "Male" , "Lebanon" , "30 to 39" , 26 ) ,
    CoffeeData( 8 , 4 , "While coding" , "Sometimes" , "Turkish" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 27 ) ,
    CoffeeData( 7 , 1 , "Before coding" , "Yes" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 28 ) ,
    CoffeeData( 2 , 2 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "40 to 49" , 29 ) ,
    CoffeeData( 10 , 6 , "All the time" , "No" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 30 ) ,
    CoffeeData( 2 , 2 , "While coding" , "No" , "Nescafe" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 31 ) ,
    CoffeeData( 9 , 2 , "Before coding" , "Sometimes" , "Nescafe" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 32 ) ,
    CoffeeData( 4 , 1 , "Before coding" , "Yes" , "Nescafe" , "No" , "Male" , "Lebanon" , "30 to 39" , 33 ) ,
    CoffeeData( 6 , 2 , "While coding" , "Sometimes" , "Espresso (Short Black)" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 34 ) ,
    CoffeeData( 2 , 2 , "While coding" , "Yes" , "American Coffee" , "No" , "Male" , "Lebanon" , "30 to 39" , 35 ) ,
    CoffeeData( 2 , 3 , "All the time" , "Sometimes" , "Turkish" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 36 ) ,
    CoffeeData( 7 , 7 , "After coding" , "Yes" , "Turkish" , "Yes" , "Female" , "Lebanon" , "40 to 49" , 37 ) ,
    CoffeeData( 1 , 1 , "While coding" , "Yes" , "Cappuccino" , "Yes" , "Male" , "Lebanon" , "40 to 49" , 38 ) ,
    CoffeeData( 4 , 2 , "While coding" , "Yes" , "Turkish" , "No" , "Male" , "Lebanon" , "50 to 59" , 39 ) ,
    CoffeeData( 8 , 2 , "While coding" , "Sometimes" , "Turkish" , "No" , "Male" , "Lebanon" , "30 to 39" , 40 ) ,
    CoffeeData( 8 , 4 , "While coding" , "Sometimes" , "Turkish" , "Yes" , "Male" , "Lebanon" , "30 to 39" , 41 ) ,
    CoffeeData( 3 , 2 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Female" , "Lebanon" , "30 to 39" , 42 ) ,
    CoffeeData( 10 , 6 , "While coding" , "Sometimes" , "NA" , "No" , "Male" , "Lebanon" , "18 to 29" , 43 ) ,
    CoffeeData( 3 , 2 , "After coding" , "Yes" , "Espresso (Short Black)" , "Sometimes" , "Male" , "Lebanon" , "40 to 49" , 44 ) ,
    CoffeeData( 7 , 2 , "While coding" , "Sometimes" , "American Coffee" , "No" , "Female" , "Lebanon" , "18 to 29" , 45 ) ,
    CoffeeData( 2 , 1 , "While coding" , "Sometimes" , "Caffè latte" , "No" , "Female" , "Lebanon" , "18 to 29" , 46 ) ,
    CoffeeData( 9 , 1 , "In the morning" , "Yes" , "Nescafe" , "No" , "Female" , "Lebanon" , "18 to 29" , 47 ) ,
    CoffeeData( 8 , 2 , "Before coding" , "No" , "Nescafe" , "No" , "Female" , "Lebanon" , "18 to 29" , 48 ) ,
    CoffeeData( 6 , 1 , "Before coding" , "Yes" , "Nescafe" , "No" , "Male" , "Lebanon" , "30 to 39" , 49 ) ,
    CoffeeData( 6 , 1 , "Before coding" , "Yes" , "Nescafe" , "No" , "Male" , "Lebanon" , "30 to 39" , 50 ) ,
    CoffeeData( 8 , 3 , "While coding" , "Sometimes" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 51 ) ,
    CoffeeData( 8 , 2 , "Before coding" , "Sometimes" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 52 ) ,
    CoffeeData( 3 , 3 , "While coding" , "No" , "Turkish" , "No" , "Male" , "Lebanon" , "18 to 29" , 53 ) ,
    CoffeeData( 7 , 4 , "No specific time" , "Yes" , "Cappuccino" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 54 ) ,
    CoffeeData( 4 , 7 , "Before and while coding" , "No" , "Double Espresso (Doppio)" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 55 ) ,
    CoffeeData( 6 , 4 , "While coding" , "Sometimes" , "Espresso (Short Black)" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 56 ) ,
    CoffeeData( 10 , 8 , "While coding" , "No" , "Turkish" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 57 ) ,
    CoffeeData( 8 , 2 , "While coding" , "Sometimes" , "Turkish" , "No" , "Male" , "Lebanon" , "18 to 29" , 58 ) ,
    CoffeeData( 2 , 4 , "While coding" , "Sometimes" , "Cappuccino" , "Sometimes" , "Male" , "Lebanon" , "40 to 49" , 59 ) ,
    CoffeeData( 6 , 2 , "Before coding" , "Yes" , "Caffè latte" , "No" , "Male" , "Lebanon" , "18 to 29" , 60 ) ,
    CoffeeData( 7 , 4 , "While coding" , "No" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 61 ) ,
    CoffeeData( 8 , 2 , "While coding" , "Sometimes" , "Turkish" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 62 ) ,
    CoffeeData( 7 , 4 , "Before coding" , "No" , "Turkish" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 63 ) ,
    CoffeeData( 8 , 4 , "While coding" , "No" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 64 ) ,
    CoffeeData( 8 , 2 , "Before coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 65 ) ,
    CoffeeData( 6 , 1 , "In the morning" , "Yes" , "Nescafe" , "No" , "Female" , "Lebanon" , "30 to 39" , 66 ) ,
    CoffeeData( 10 , 2 , "While coding" , "Sometimes" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 67 ) ,
    CoffeeData( 8 , 4 , "Before and while coding" , "No" , "Turkish" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 68 ) ,
    CoffeeData( 10 , 6 , "While coding" , "Sometimes" , "Double Espresso (Doppio)" , "No" , "Male" , "Lebanon" , "30 to 39" , 69 ) ,
    CoffeeData( 6 , 4 , "While coding" , "Sometimes" , "Espresso (Short Black)" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 70 ) ,
    CoffeeData( 10 , 8 , "All the time" , "No" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 71 ) ,
    CoffeeData( 5 , 5 , "While coding" , "Sometimes" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 72 ) ,
    CoffeeData( 8 , 4 , "Before and while coding" , "Sometimes" , "Turkish" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 73 ) ,
    CoffeeData( 4 , 2 , "While coding" , "No" , "Nescafe" , "Yes" , "Female" , "Lebanon" , "18 to 29" , 74 ) ,
    CoffeeData( 6 , 6 , "While coding" , "Sometimes" , "Cappuccino" , "No" , "Male" , "Lebanon" , "18 to 29" , 75 ) ,
    CoffeeData( 8 , 2 , "While coding" , "Sometimes" , "Nescafe" , "Sometimes" , "Male" , "Lebanon" , "30 to 39" , 76 ) ,
    CoffeeData( 9 , 3 , "While coding" , "Sometimes" , "Nescafe" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 77 ) ,
    CoffeeData( 7 , 2 , "While coding" , "Sometimes" , "Caffè latte" , "No" , "Male" , "Lebanon" , "18 to 29" , 78 ) ,
    CoffeeData( 4 , 5 , "While coding" , "Sometimes" , "American Coffee" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 79 ) ,
    CoffeeData( 2 , 1 , "While coding" , "Yes" , "Nescafe" , "No" , "Male" , "Lebanon" , "18 to 29" , 80 ) ,
    CoffeeData( 7 , 3 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 81 ) ,
    CoffeeData( 6 , 3 , "While coding" , "Yes" , "Nescafe" , "Yes" , "Female" , "Lebanon" , "18 to 29" , 82 ) ,
    CoffeeData( 3 , 3 , "While coding" , "Sometimes" , "Caffè latte" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 83 ) ,
    CoffeeData( 10 , 2 , "While coding" , "Yes" , "American Coffee" , "No" , "Male" , "Lebanon" , "18 to 29" , 84 ) ,
    CoffeeData( 10 , 3 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 85 ) ,
    CoffeeData( 3 , 1 , "While coding" , "Sometimes" , "Nescafe" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 86 ) ,
    CoffeeData( 3 , 3 , "While coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 87 ) ,
    CoffeeData( 9 , 7 , "All the time" , "No" , "Espresso (Short Black)" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 88 ) ,
    CoffeeData( 10 , 1 , "Before coding" , "Sometimes" , "American Coffee" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 89 ) ,
    CoffeeData( 7 , 1 , "Before coding" , "Sometimes" , "Cappuccino" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 90 ) ,
    CoffeeData( 5 , 3 , "While coding" , "Sometimes" , "Turkish" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 91 ) ,
    CoffeeData( 5 , 2 , "Before coding" , "Sometimes" , "Nescafe" , "Yes" , "Female" , "Lebanon" , "18 to 29" , 92 ) ,
    CoffeeData( 3 , 1 , "Before coding" , "Yes" , "Nescafe" , "No" , "Female" , "Lebanon" , "18 to 29" , 93 ) ,
    CoffeeData( 4 , 2 , "While coding" , "Yes" , "Nescafe" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 94 ) ,
    CoffeeData( 6 , 2 , "Before coding" , "Yes" , "Nescafe" , "Yes" , "Male" , "Lebanon" , "18 to 29" , 95 ) ,
    CoffeeData( 4 , 1 , "Before coding" , "Sometimes" , "Nescafe" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 96 ) ,
    CoffeeData( 10 , 3 , "Before coding" , "Yes" , "Cappuccino" , "Yes" , "Male" , "Lebanon" , "Under 18" , 97 ) ,
    CoffeeData( 2 , 2 , "While coding" , "Sometimes" , "Espresso (Short Black)" , "Sometimes" , "Female" , "Lebanon" , "18 to 29" , 98 ) ,
    CoffeeData( 10 , 4 , "Before coding" , "Sometimes" , "Double Espresso (Doppio)" , "Sometimes" , "Male" , "Lebanon" , "18 to 29" , 99 )  ];
}